// Resource-specific page mappings generated by Terrazzo.
// Add manual custom pages to custom_page_mapping.js instead.

// Terrazzo generated page imports start
import CustomerIndex from "../../views/admin/customers/index";
import OrderShow from "../../views/admin/orders/show";
// Terrazzo generated page imports end

export const generatedPageMapping = {
  // Terrazzo generated page mappings start
  'admin/customers/index': CustomerIndex,
  'admin/orders/show': OrderShow,
  // Terrazzo generated page mappings end
}
