require "terrazzo/base_dashboard"

# Test fixture dashboard used by unit specs.
# This is NOT in the example app because the example app's dashboards
# are generated by terrazzo:install and don't exist in the base state.
class CustomerDashboard < Terrazzo::BaseDashboard
  ATTRIBUTE_TYPES = {
    id: Terrazzo::Field::Number,
    name: Terrazzo::Field::String.with_options(searchable: true),
    email: Terrazzo::Field::Email.with_options(searchable: true),
    created_at: Terrazzo::Field::DateTime,
    updated_at: Terrazzo::Field::DateTime,
    email_subscriber: Terrazzo::Field::Boolean,
    kind: Terrazzo::Field::Select.with_options(collection: ["standard", "vip"]),
    example_time: Terrazzo::Field::Time,
    password: Terrazzo::Field::Password,
    hidden: Terrazzo::Field::Boolean,
    orders: Terrazzo::Field::HasMany,
    territory: Terrazzo::Field::BelongsTo,
    log_entries: Terrazzo::Field::HasMany,
  }.freeze

  COLLECTION_ATTRIBUTES = %i[
    id
    name
    email
    kind
    territory
  ].freeze

  SHOW_PAGE_ATTRIBUTES = %i[
    id
    name
    email
    created_at
    updated_at
    email_subscriber
    kind
    example_time
    password
    hidden
    orders
    territory
    log_entries
  ].freeze

  FORM_ATTRIBUTES = %i[
    name
    email
    email_subscriber
    kind
    example_time
    password
    hidden
    orders
    territory
    log_entries
  ].freeze
end
