module Terrazzo
  module Generators
    module Views
      module PageMappingHelper
        GENERATED_IMPORT_MARKER = "// Terrazzo generated page imports end"
        GENERATED_MAPPING_MARKER = "  // Terrazzo generated page mappings end"

        private

        def register_page_mapping(action)
          mapping_path = "app/javascript/#{namespace_name}/generated_page_mapping.js"
          mapping_file = File.join(destination_root, mapping_path)

          unless File.exist?(mapping_file)
            create_file mapping_path, <<~JS
              // Resource-specific page mappings generated by Terrazzo.
              // Add manual custom pages to custom_page_mapping.js instead.

              // Terrazzo generated page imports start
              // Terrazzo generated page imports end

              export const generatedPageMapping = {
                // Terrazzo generated page mappings start
                // Terrazzo generated page mappings end
              }
            JS
          end

          component_name = "#{resource.gsub('::', '')}#{action.capitalize}"
          import_path = "../../views/#{namespace_name}/#{resource_path}/#{action}"
          key = "'#{namespace_name}/#{resource_path}/#{action}'"

          content = File.read(mapping_file)
          return if content.include?(key)

          ensure_generated_mapping_loaded

          import_line = "import #{component_name} from \"#{import_path}\";\n"
          insert_generated_import(mapping_path, content, import_line, component_name)

          entry_line = "  #{key}: #{component_name},\n"
          insert_generated_mapping_entry(mapping_path, File.read(mapping_file), entry_line, key)
        end

        def ensure_generated_mapping_loaded
          main_mapping_path = "app/javascript/#{namespace_name}/page_to_page_mapping.js"
          main_mapping_file = File.join(destination_root, main_mapping_path)
          return unless File.exist?(main_mapping_file)

          content = File.read(main_mapping_file)

          unless content.include?("generatedPageMapping")
            import_line = %(import { generatedPageMapping } from "./generated_page_mapping";\n)
            if content.include?(%(import { customPageMapping } from "./custom_page_mapping";))
              inject_into_file main_mapping_path, import_line,
                before: %(import { customPageMapping } from "./custom_page_mapping";)
            else
              prepend_to_file main_mapping_path, import_line
            end
            content = File.read(main_mapping_file)
          end

          return if content.include?("...generatedPageMapping")

          generated_spread = "  ...generatedPageMapping,\n"
          if content.include?("  ...customPageMapping,")
            inject_into_file main_mapping_path, generated_spread, before: "  ...customPageMapping,"
          elsif content.include?("...customPageMapping")
            gsub_file main_mapping_path, "...customPageMapping", "...generatedPageMapping, ...customPageMapping"
          elsif content.include?("const pages = {\n")
            inject_into_file main_mapping_path, generated_spread, after: "const pages = {\n"
          else
            say_status :warning,
              "#{main_mapping_path} imports generated_page_mapping.js but Terrazzo could not find the pages object to merge it automatically.",
              :yellow
          end
        end

        def insert_generated_import(mapping_path, content, import_line, component_name)
          if content.include?(GENERATED_IMPORT_MARKER)
            inject_into_file mapping_path, import_line, before: GENERATED_IMPORT_MARKER
          elsif content.include?("export const generatedPageMapping")
            prepend_to_file mapping_path, import_line
            say_status :warning,
              "#{mapping_path} is missing #{GENERATED_IMPORT_MARKER.inspect}; prepended #{component_name} import.",
              :yellow
          else
            raise Thor::Error,
              "#{mapping_path} must export generatedPageMapping so Terrazzo can register resource-specific pages."
          end
        end

        def insert_generated_mapping_entry(mapping_path, content, entry_line, key)
          if content.include?(GENERATED_MAPPING_MARKER)
            inject_into_file mapping_path, entry_line, before: GENERATED_MAPPING_MARKER
          elsif content.include?("export const generatedPageMapping = {\n")
            inject_into_file mapping_path, entry_line, after: "export const generatedPageMapping = {\n"
            say_status :warning,
              "#{mapping_path} is missing #{GENERATED_MAPPING_MARKER.strip.inspect}; inserted #{key} at the start of generatedPageMapping.",
              :yellow
          else
            raise Thor::Error,
              "#{mapping_path} must export generatedPageMapping so Terrazzo can register #{key}."
          end
        end
      end
    end
  end
end
